/* EXPECTED_OUTCOME */
/* One row per employee per rate type — the shape we'll build */
let
  Source = Table.FromRows(
    {
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.2", 5, 300.33},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.33", 3, 400.44},
      {785, "Cadbury",  #date(2026, 6, 6), "OT @1.5", 1, 600.66}
    }, type table [
      Employee=Int64.Type,Company=text, Work date=date, Rate Type=text, Hours=number, Cost=number
    ]
  )
in
  Source
