/* RAW_DATA used in: Solution1 */
/* Layout: Hours and Cost are paired per rate — OT Hours @x followed by OT Cost @x */

let
  Source = Table.FromRows(
    {
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66},
      {785, "Cadbury",  #date(2026, 6, 6), 5, 300.33, 3, 400.44, 1, 600.66}
    }, type table [
      Employee= Int64.Type, Company=text, Work date=date, #"OT Hours @1.2"=number, #"OT Cost @1.2"=number, #"OT Hours @1.33"=number, #"OT Cost @1.33"=number, #"OT Hours @1.5"=number, #"OT Cost @1.5"=number
    ]
  )
in
  Source
