/* RAW_DATA2 used in: Solution2 */
/* Layout: all Hours columns appear first, followed by all Cost columns */

let
  Source = Table.FromRows(
    {
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66},
      {785, "Cadbury", #date(2026, 6, 6), 5, 3, 1, 300.33, 400.44, 600.66}
    }, type table [
      Employee= Int64.Type, Company=text, Work date=date, #"OT Hours @1.2"=number, #"OT Hours @1.33"=number, #"OT Hours @1.5"=number, #"OT Cost @1.2"=number, #"OT Cost @1.33"=number, #"OT Cost @1.5"=number
    ]
  )
in
  Source
